"""pages/2_Cash_Flows.py — Cash Flow Valuation with live data auto-fill"""
import streamlit as st
import pandas as pd
import math
from data_fetcher import get_company_data, source_badge_html
from fcff_models import fcff_2stage, FCFFValuationResult
from cost_of_capital import full_cost_of_capital

st.set_page_config(page_title="Cash Flow Valuation", page_icon="💵", layout="wide")
pg_id = "2"

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display&family=DM+Sans:wght@300;400;500&display=swap');
html, body, [class*="css"] { font-family: 'DM Sans', sans-serif; }
h1, h2, h3 { font-family: 'DM Serif Display', serif; }
.explain-box { background:#1e293b; border-left:3px solid #3b82f6; border-radius:0 8px 8px 0; padding:14px 18px; margin:10px 0 18px 0; font-size:0.88rem; line-height:1.7; color:#cbd5e1; }
.score-pill { display:inline-block; padding:3px 12px; border-radius:20px; font-size:0.8rem; font-weight:500; margin-top:8px; }
.score-green  { background:#14532d; color:#86efac; }
.score-yellow { background:#713f12; color:#fde68a; }
.score-red    { background:#7f1d1d; color:#fca5a5; }
</style>
""", unsafe_allow_html=True)

def badge(s, t, c): return f'<span class="score-pill score-{c}">Score {s}/10 — {t[:60]}</span>'

def score_tv(tv_pct):
    if tv_pct < .50: return 9,"Low TV dependence — most value from near-term cash flows","green"
    elif tv_pct < .65: return 7,"Moderate TV dependence — typical for stable businesses","green"
    elif tv_pct < .80: return 5,"High TV dependence — sensitive to stable-growth assumptions","yellow"
    else: return 3,"Very high TV dependence (>80%) — treat terminal value assumptions with care","red"

def score_mos(price, value):
    if price <= 0 or value <= 0: return 5,"Enter price for margin of safety","yellow"
    r = value/price
    if r > 1.5: return 10,f"Large margin of safety — value is {r:.1f}× price","green"
    elif r > 1.2: return 8,f"Good margin of safety — {r:.1f}× price","green"
    elif r > 0.9: return 6,f"Fairly valued — {r:.1f}× price","yellow"
    elif r > 0.7: return 4,f"Mild overvaluation — price is {1/r:.1f}× value","yellow"
    else: return 2,f"Significant overvaluation — price is {1/r:.1f}× value","red"

def explain(key, explanations):
    e = explanations.get(key,{})
    if not e: return
    with st.expander(f"📖 What is {e['title']}?", expanded=False):
        st.markdown(f'<div class="explain-box"><strong>What it is:</strong> {e["what"]}<br><br><strong>Formula:</strong> <code>{e["formula"]}</code><br><br><strong>Why it matters:</strong> {e["why"]}<br><br><div style="font-size:0.72rem;color:#475569">📚 {e["source"]}</div></div>', unsafe_allow_html=True)

EXPL = {
    "fcff": {"title":"FCFF","what":"Cash generated by operations after reinvestment, before debt/equity payments.","formula":"FCFF = EBIT×(1−t) − Net_CapEx − ΔWC","why":"Discount at WACC to get firm value, then subtract debt to get equity value.","source":"Damodaran, Ch 10, p.247"},
    "tv": {"title":"Terminal Value","what":"PV of all cash flows beyond the explicit forecast, as a growing perpetuity.","formula":"TV = FCFF_{n+1} / (WACC − g_stable)","why":"Typically 60–80% of firm value. g_stable must be ≤ risk-free rate.","source":"Damodaran, Ch 12, p.303"},
    "rir": {"title":"Reinvestment Rate","what":"Fraction of NOPAT reinvested to sustain growth.","formula":"RIR = (Net_CapEx + ΔWC) / NOPAT  =  g / ROC","why":"Growth only creates value when ROC > WACC.","source":"Damodaran, Ch 11, p.280"},
}

# ── Sidebar ──────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("## 💵 Cash Flow Valuation")

    d = st.session_state.get("company_data")
    if d:
        st.markdown(source_badge_html(d), unsafe_allow_html=True)
        st.caption(f"{d.name}")
    else:
        st.warning("No data loaded. Go to the home page and click **Load company data**.")

    st.markdown("---")
    st.markdown("### Growth assumptions")
    g_high  = st.number_input("High-growth rate",    value=0.10, format="%.3f", key=f"gh_{pg_id}")
    n_high  = int(st.number_input("High-growth years", value=5, step=1, key=f"nh_{pg_id}"))
    g_stable= st.number_input("Stable growth rate",  value=0.03, format="%.3f", key=f"gs_{pg_id}")
    roc_s   = st.number_input("Stable ROC",           value=0.12, format="%.3f", key=f"rs_{pg_id}")
    st.markdown("### Market data")
    price   = st.number_input("Current price ($)", value=float(d.price) if d else 0.0, key=f"pr_{pg_id}")
    shares  = st.number_input("Shares (m)",        value=float(d.shares) if d and d.shares else 1000.0, key=f"sh_{pg_id}")

# ── Header ────────────────────────────────────────────────────────────────────
name = d.name if d else "—"
st.title(f"💵 Cash Flow Valuation — {name}")
st.markdown("**FCFF 2-stage model** · Damodaran Ch 10, 15 · fcff2st.xls · fcffginzu.xlsx")

if not d:
    st.info("Enter a ticker in the sidebar and click **🔄 Fetch live data** to run the model.")
    st.stop()

st.markdown(source_badge_html(d), unsafe_allow_html=True)
if d.fetch_errors:
    with st.expander("⚠ Data warnings"): [st.caption(e) for e in d.fetch_errors]
st.divider()

# ── Get WACC from CoC module if available, else compute inline ───────────────
coc_key = f"coc_{ticker}_{pg_id}"
if coc_key not in st.session_state:
    try:
        coc = full_cost_of_capital(
            ebit=d.ebit, interest_expense=d.interest_expense,
            book_debt=d.book_debt, avg_debt_maturity=d.avg_debt_maturity,
            equity_market_cap=d.equity_market_cap, beta_levered=d.beta_levered,
            rf=d.rf, erp=d.erp, tax_rate=d.tax_rate,
            country_spread=d.country_spread, firm_type=d.firm_type,
        )
        st.session_state[coc_key] = coc
    except Exception as e:
        st.session_state[coc_key] = None

coc = st.session_state.get(coc_key)
wacc_val = coc.wacc_result.wacc if coc else 0.09

# ── Inputs (pre-filled from live data, editable) ─────────────────────────────
st.markdown("## Inputs")
st.caption("Pre-filled from live data · adjust any value before calculating")

col1, col2 = st.columns(2)
with col1:
    st.markdown("**Current financials** (from yfinance)")
    ebit  = st.number_input("EBIT ($m)",              value=float(d.ebit),            key="fi_ebit")
    tax   = st.number_input("Tax rate",               value=float(d.tax_rate),        key="fi_tax",  format="%.3f")
    capex = st.number_input("CapEx ($m)",             value=float(d.capex),           key="fi_capex")
    depr  = st.number_input("Depreciation ($m)",      value=float(d.depreciation),    key="fi_depr")
    dwc   = st.number_input("ΔWorking Capital ($m)",  value=float(d.delta_wc),        key="fi_dwc")
    rev   = st.number_input("Revenue ($m)",           value=float(d.revenue),         key="fi_rev")
    debt  = st.number_input("Debt MV ($m)",           value=float(d.book_debt),       key="fi_debt")
    cash_v= st.number_input("Cash ($m)",              value=float(d.cash),            key="fi_cash")

with col2:
    st.markdown("**Discount rates** (from Module 01 / FRED)")
    wacc_h= st.number_input("WACC (high growth)",     value=round(wacc_val,4),        key="fi_wh",   format="%.4f")
    wacc_s= st.number_input("WACC (stable)",          value=round(wacc_val*0.95,4),   key="fi_ws",   format="%.4f")
    wc_pct= st.number_input("WC as % of revenues",   value=round(d.delta_wc/d.revenue,4) if d.revenue>0 else 0.05, key="fi_wcp", format="%.4f")
    if coc:
        st.markdown(f"""<div class="explain-box" style="margin-top:12px">
<strong>WACC from Module 01:</strong> {coc.wacc_result.wacc:.2%}<br>
ke = {coc.beta_result.ke:.2%} · kd = {coc.debt_cost.kd_aftertax:.2%}<br>
Rating: {coc.debt_cost.rating} · ICR: {coc.debt_cost.icr:.1f}×
</div>""", unsafe_allow_html=True)

explain("fcff", EXPL); explain("rir", EXPL)

# ── Run model automatically ───────────────────────────────────────────────────
st.divider()
st.markdown("## Results")

try:
    r = fcff_2stage(
        ebit=ebit, tax_rate=tax, capex=capex, depreciation=depr,
        delta_wc=dwc, revenues=rev,
        wacc_high=wacc_h, g_high=g_high, n_high=n_high,
        g_stable=g_stable, wacc_stable=wacc_s, stable_roc=roc_s,
        wc_pct_rev=wc_pct,
        debt_mv=debt, cash=cash_v, shares=shares,
    )

    tv_pct = r.pv_terminal_value / r.value_of_firm if r.value_of_firm > 0 else 0

    # Top metrics
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Value of Firm",   f"${r.value_of_firm:,.0f}m")
    c2.metric("Value of Equity", f"${r.value_of_equity:,.0f}m")
    c3.metric("Value / Share",   f"${r.value_per_share:,.2f}",
              delta=f"{(r.value_per_share/price-1)*100:+.1f}% vs price" if price > 0 else None)
    c4.metric("Terminal Value %",f"{tv_pct:.0%}")

    s_tv,t_tv,c_tv = score_tv(tv_pct)
    st.markdown(badge(s_tv,t_tv,c_tv), unsafe_allow_html=True)
    if price > 0:
        s_m,t_m,c_m = score_mos(price, r.value_per_share)
        st.markdown("&nbsp;&nbsp;" + badge(s_m,t_m,c_m), unsafe_allow_html=True)

    # Value bridge
    st.markdown(f"""<div class="explain-box">
<strong>Value bridge:</strong><br>
PV high-growth FCFFs: <strong>${r.pv_fcff_highgrowth:,.0f}m</strong><br>
PV terminal value: <strong>${r.pv_terminal_value:,.0f}m</strong> ({tv_pct:.0%} of firm value)<br>
= Firm value: <strong>${r.value_of_firm:,.0f}m</strong><br>
− Debt: ${r.debt_mv:,.0f}m &nbsp; + Cash: ${r.cash:,.0f}m<br>
= Equity: <strong>${r.value_of_equity:,.0f}m</strong> ÷ {r.shares:,.0f}m shares
= <strong>${r.value_per_share:,.2f}/share</strong>
</div>""", unsafe_allow_html=True)

    explain("tv", EXPL)

    # Year-by-year table
    st.markdown("#### Year-by-year cash flows")
    df = pd.DataFrame([{
        "Year": row.year, "EBIT ($m)": f"{row.ebit:,.0f}",
        "NOPAT ($m)": f"{row.nopat:,.0f}", "Net CapEx": f"{row.net_capex:,.0f}",
        "ΔWC ($m)": f"{row.delta_wc:,.0f}", "RIR": f"{row.reinvestment_rate:.1%}",
        "FCFF ($m)": f"{row.fcff:,.0f}", "WACC": f"{row.wacc:.2%}",
        "PV ($m)": f"{row.pv_fcff:,.0f}",
    } for row in r.yearly])
    st.dataframe(df, use_container_width=True, hide_index=True)

    # Terminal value detail
    st.markdown("#### Terminal value")
    col1, col2, col3 = st.columns(3)
    col1.metric("Terminal FCFF", f"${r.terminal_fcff:,.0f}m")
    col2.metric("Terminal Value", f"${r.terminal_value:,.0f}m")
    col3.metric("PV of TV", f"${r.pv_terminal_value:,.0f}m")
    st.caption(f"TV = Terminal_FCFF / (WACC_stable − g_stable) = ${r.terminal_fcff:,.0f}m / ({wacc_s:.2%} − {g_stable:.2%}) = ${r.terminal_value:,.0f}m")

except Exception as e:
    st.error(f"Model error: {e}")
    st.caption("Check that WACC > stable growth rate and all inputs are positive.")

st.divider()
st.markdown('<div style="font-size:0.75rem;color:#475569;text-align:center">Damodaran, Investment Valuation 2nd Ed. Ch 10, 15 · fcff2st.xls · fcffginzu.xlsx</div>', unsafe_allow_html=True)
